---
sudo: false
language: nix
nix: 2.2.1
env:
  - NIX_PATH=nixpkgs=channel:nixos-19.09

install:
  - nix-env -iA pkgs.python37Packages.ansible-lint pkgs.python37Packages.ansible pkgs.shellcheck -f '<nixpkgs>'
  - nix-env -if ./dhall-1.26.1.nix

  # Check ansible version
  - ansible --version

  # Alias role name to mimic actual Galaxy deployment
  - ln -s ansible-clever ../clever

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-lint .
  - shellcheck **/*.sh
  - scripts/dhall_check.sh

notifications:
  slack: fretlink:pTIylIN7zkwRFuL3aHERmsbB
