---
language: nix

sudo: false

install:
  - nix-env -i python2.7-ansible
  - nix-env -i python2.7-ansible-lint
  - nix-env -if ./dhall-1.18.nix

  # Check ansible version
  - ansible --version

  # Alias role name to mimic actual Galaxy deployment
  - ln -s ansible-clever ../clever

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-lint .
  - scripts/dhall_check.sh

notifications:
  slack: fretlink:pTIylIN7zkwRFuL3aHERmsbB
