---
sudo: false
language: nix
nix: 2.2.1
env:
  - NIX_PATH=nixpkgs=channel:nixos-19.09

install:
  - nix-env -iA pkgs.python37Packages.ansible-lint pkgs.python37Packages.ansible pkgs.shellcheck -f '<nixpkgs>'
  - nix-env -if ./dhall-1.26.1.nix

  # Check ansible version
  - ansible --version

  # Alias role name to mimic actual Galaxy deployment
  - ln -s ansible-clever ../clever

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check & linting
  - ansible-lint .
  - shellcheck **/*.sh
  - scripts/dhall_check.sh
  # Run integration test
  - mkdir -p ~/.local/bin
  - cp tests/fake.sh ~/.local/bin/clever
  - cp tests/fake.sh ~/.local/bin/git
  - ansible-playbook tests/test-simple-app.yml -i tests/inventory
  - ansible-playbook tests/test-haskell-app.yml -i tests/inventory
  - ansible-playbook tests/test-configure-app.yml -i tests/inventory
  - ansible-playbook tests/test-scalability.yml -i tests/inventory

notifications:
  slack: fretlink:pTIylIN7zkwRFuL3aHERmsbB
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
