- name: Create .clever-cloud directory
  file:
    path: "{{ clever_app_confdir }}"
    state: directory

- name: Fill the login file
  template:
    src: cleverlogin.j2
    dest: "{{ clever_login_file }}"
  no_log: true

- name: Link app
  command: clever link {{ clever_app }}
  args:
    creates: "{{ clever_app_root }}/.clever.json"
  environment:
    CONFIGURATION_FILE: "{{ clever_login_file }}"
