---
# tasks file for clever
- name: Setup environment for clever
  import_tasks: setup.yml
  tags:
    - clever
    - clever-setup

- name: Login to clever
  import_tasks: login.yml
  tags:
    - clever
    - clever-login

- name: Manage environment
  import_tasks: environment.yml
  tags:
    - clever
    - clever-env

- name: Include specific tasks
  include_tasks: "{{ clever_app_tasks_file }}"
  when: clever_app_tasks_file is defined

- name: Deploy app
  import_tasks: deploy.yml
  when: not clever_restart_only is defined or not clever_restart_only
  tags:
    - clever
    - clever-deploy

- name: Post deploy tasks
  import_tasks: post_deploy.yml
  when: not clever_restart_only is defined or not clever_restart_only
  tags:
    - clever
    - clever-deploy
    - clever-env

- name: Restart app
  import_tasks: restart.yml
  when: clever_restart_only is defined and clever_restart_only
  tags:
    - clever
    - clever-restart
